### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [Meir017/Cake.Openshift#4]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by Meir017** [comment]
I added the user @cake-contrib pending approval

**Comment by gep13** [comment]
@Meir017 that is great, thank you very much.  I have accepted the invite 😄

**Comment by gep13** [comment]
@Meir017 related to this, let me know if you are interested in moving this project under the Cake-Contrib Organisation on GitHub.  You would have the same access rights to the repository as you do now, it is just that it would live under the Cake-Contrib Organisation.

**Comment by Meir017** [comment]
@gep13 Yup!

**Comment by gep13** [comment]
@Meir017 The process for adding to the Cake-Contrib Organisation is documented here: https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

**Comment by Meir017** [comment]
@gep13 Can I make you the owner of the repository so you can move it into the `cake-contrib` org?

**Comment by gep13** [comment]
@Meir017 unfortunately not, no.  I have tried various different combinations, and the only one that seems to work reliably is to do an individual to individual transfer, and then I can move it into the Cake-Contrib Organisation.

**Comment by gep13** [comment]
@Meir017 the steps needed to transfer the repository into the Organisation are just about complete.

I am currently running a script to synchronise GitHub permissions over to AppVeyor.  Once that work is complete, you should have all the access that you need.

Please let me know if you have any questions.

**Comment by Meir017** [comment]
I noticed that the cake main repo creates the releases automatically when the current milestone is completed, how is that done?
I saw the `GitReleaseManager` tool being used in the `.cake` scripts but I couldn't put it all together

**Comment by gep13** [comment]
@Meir017 most of the addins that are in the Cake-Contrib Organisation now make use of the Cake.Recipe set of re-usable scripts.  This takes care of most things, like compilation, style checking, publishing to MyGet, publishing to NuGet, generating release notes, etc.

You can find the repo here:

https://github.com/cake-contrib/Cake.Recipe

And some documentation here:

https://cake-contrib.github.io/Cake.Recipe/docs/

If you are interested, we can switch this repository to use Cake.Recipe and to start taking advantage of that.

**Comment by Meir017** [comment]
I would like to do that

**Comment by gep13** [comment]
Sweet!  Are you happy to have a read through the documentation and compare to other repos that are using it, or how would you like to get started?

**Comment by Meir017** [comment]
found this while trying to use `Cake.Recipe` https://github.com/cake-build/bakery/issues/77

**Comment by gep13** [comment]
Ouch! That is definitely an issue 😢

**Comment by Meir017** [comment]
#9
